### PR TITLE
Fix bootloop on Android Q

### PR DESCRIPTION
**Pull request by kotori2**
I fixed permission issue which cause bootloop in upstream library `whale`.
Modified source code can be found [here](https://github.com/kotori2/whale/commit/b1cde54f16d4ed3bf7119201360db6fa699fafda).
Only tested on Android Q OB1 on OP7P.
Compiled zip file was attached below.
[magisk-EdXposed-YAHFA-v0.4.5.5_beta-release.zip](https://github.com/ElderDrivers/EdXposed/files/3613663/magisk-EdXposed-YAHFA-v0.4.5.5_beta-release.zip)

Edit: SandHook was also fixed. Also I changed version number to 0.4.6.0.
[magisk-EdXposed-SandHook-v0.4.6.0_beta-release.zip](https://github.com/ElderDrivers/EdXposed/files/3616007/magisk-EdXposed-SandHook-v0.4.6.0_beta-release.zip)

### CODE REVIEW

**Comment by coderstory** [comment]
mi9 miui10 anroid Q
boot success

**Comment by eebssk1** [comment]
android 9成功翻车。日志暂未获取。

**Comment by eebssk1** [comment]
找到问题了。找不到libandroid_servers.so

**Comment by eebssk1** [comment]
art初始化过早了，那个时候64位的liband......还没被镜像

**Comment by jamesli1258** [comment]
多謝你幫忙我們

**Comment by reyqn** [comment]
Booted without any issue on my pixel 3a (android Q stock)

**Comment by kotori2** [comment]
> 找到问题了。找不到libandroid_servers.so

并没有动过启动顺序。如果你用我这个崩的话，用官方release应该也会崩？
@eebssk1

**Comment by singleNeuron** [comment]
Screenshot_2019-09-16-18-54-10-626_com solohsu android edxp manager
It works on mi 9 MIUI 9.8.29, thx for your work a lot

**Comment by eebssk1** [comment]
> 
> 
> > 找到问题了。找不到libandroid_servers.so
> 
> 并没有动过启动顺序。如果你用我这个崩的话，用官方release应该也会崩？
> @eebssk1

我知道。。我也很奇怪啊，我一直用的官方4468，一换上你的就会这样，，，，真是玄学。。

**Comment by kotori2** [comment]
@eebssk1 机型和系统？

**Comment by HpNoTiQ56** [comment]
Working great with xposed modules loading and working (YBPB, LP, ChromePie, ...) I Only miss gravity box!

**Comment by eebssk1** [comment]
> 
> 
> @eebssk1 机型和系统？

Xiaomi Mi6(sagit)
RR-P-v7.0.2

**Comment by s3axel** [comment]
Also working great here on another OP7Pro with OB1 - thanks !!

**Comment by singleNeuron** [comment]
疑似黑名单无效，会导致云闪付无法启动，未验证
mi9，MIUI 9.8.29

**Comment by zhanglianxin** [comment]
Working great on Xiaomi Mi6 (sagit) PixelExperience_sagit-10.0 (Android 10), thanks!

**Comment by DarkSJ1998** [comment]
@s3axel Does it also work fine on OB2? Some guy on XDA reported he faced bootloop. And you're using Sandhook or Yahfa?

**Comment by s3axel** [comment]
Works also on OB2. Here I'm presently using Sandhook, haven't tested YAHFA...

**Comment by tardeaux** [comment]
I also had a bootloop on OP7pro, but uninstalling XPrivacyLUA resolved it. Don't forget to disable your modules before upgrading from Pie 😉

**Comment by Rakau** [comment]
MIUI10 安卓10 Working magisk-EdXposed-SandHook-v0.4.6.0_beta-release.zip

**Comment by AlienHack** [comment]
Confirmed working on Android O with one plus 7 pro

**Comment by infoflo7** [comment]
Screenshot_20190924-132911_EdXposed_Installer

Works on Redmi Note 7 on Android 10 custom ROM (Atom OS)! Thanks!

**Comment by nialler82** [comment]
Can @alienhack please link me to the edxposed manager that installed for them on oneplus 7 pro, Android q stable. I cannot get any to install for me. Thanks

**Comment by limstash** [comment]
Still bootloop on Xiaomi MI 8 with Pixel Experience ROM

**Comment by jamesli1258** [comment]
I also can't boot after reinstalling this edxposed.

**Comment by SukkaW** [comment]
OnePlus 7 with OxygenOS 10.0 Boot successfully.

**Comment by nialler82** [comment]
Booting successfully on Op7pro.

**Comment by junk099** [comment]
Working !

Xiaomi Mi 9 
MIUI 11 (9.9.26)
SandHook-v0.4.6.0_beta

**Comment by neejay** [comment]
Not working on pixel 2xl Q/10 QP1A. (I can boot, but the Xposed framework isn't showing as installed via EdXposed installer)

**Comment by junk099** [comment]
> Not working on pixel 2xl Q/10 QP1A. (I can boot, but the Xposed framework isn't showing as installed via EdXposed installer)

Had same thing on YAHFA, but SandHook works like a charm. (Mi9, miui 9.9.26)

**Comment by 5night** [comment]
Working!

Xiaomi Mi 9 (cepheus)
Android 10 Q
MIUI 11 (9.9.27)
magisk-EdXposed-YAHFA-v0.4.5.5

Thanks!

**Comment by Mich3le3D** [comment]
Not working with Xiaomi Mi MIX2S (a-only) "polaris"
Pixel3Rom
Android 10
Don't pass the boot logo, I've tried both.

**Comment by betaback** [comment]
sandhook 一加7pro氧os 安卓10 一切正常

**Comment by AlienHack** [comment]
> Can @AlienHack please link me to the edxposed manager that installed for them on oneplus 7 pro, Android q stable. I cannot get any to install for me. Thanks

https://github.com/ElderDrivers/EdXposedManager/releases

**Comment by 15933338980** [comment]
我想请教一下，安卓9能刷4.6.0吗？

**Comment by F0x1d** [comment]
stuck at bootlogo on PE Q, Redmi 5 Plus (vince)

**Comment by knaik95** [comment]
Are all of you using some other version of EdXposed or does it now support Q and the README simply hasn't been updated?

**Comment by nialler82** [comment]
@knaik95 fire ahead. Using this for ages now and no issues (YAHFA) on Oneplus 7 pro.

**Comment by gryffyn** [comment]
the sandhook built boots and runs perfectly on MIUI11 (xiaomi.eu) (Android 10) on a Xiaomi Mi 9. @knaik95 This build seems to work for a number of people on Q

**Comment by knaik95** [comment]
> @knaik95 fire ahead. Using this for ages now and no issues (YAHFA) on Oneplus 7 pro.

> the sandhook built boots and runs perfectly on MIUI11 (xiaomi.eu) (Android 10) on a Xiaomi Mi 9. @knaik95 This build seems to work for a number of people on Q

Awesome, I'll do it as soon as I have the funds (in GB) to build a Q-based ROM for my device. Also,



oops I just realized I have both SandHook and YAHFA installed. Is that okay or frowned upon?

**Comment by parambika** [comment]
> stuck at bootlogo on PE Q, Redmi 5 Plus (vince), SandHook

Same, stuck on boot logo redmi note 5 pro

**Comment by parambika** [comment]
> stuck at bootlogo on PE Q, Redmi 5 Plus (vince), SandHook

Same, stuck on boot logo redmi note 5 pro on aosp based Q rom

**Comment by kotori2** [comment]
@Mich3le3D For Xiaomi devices, someone said there is conflict between module SELinux policy and system policy, which will cause boot loop. You can try disabling `post-fs-data.sh` and execute it manually after reboot and set SELinux permissive.

**Comment by kotori2** [comment]
@knaik95 since this issue is not go to be merge forever, I'm not working on this anymore.
(maybe my code looks noob

**Comment by knaik95** [comment]
> @knaik95 since this issue is not go to be merge forever, I'm not working on this anymore.
> (maybe my code looks noob

Oh, that's okay!

**Comment by Howard20181** [comment]
Work well in Mi9 
MIUI 11 9.10.10 
Android 10

**Comment by soaresden** [comment]
Bootloop on mi8 latest time
Both sand and yahfa

Thanks mm to be able to remove each time

**Comment by KaizerHanz** [comment]
Work Well on Xiaomi Mi8 EU ROM, 9.10.11 MIUI11 Android Q, thanks to @kotori2 for pointing out bootloop, just used YAHYA version, Sandhook version give me some app "force closed" error. But YAHYA working well.

**Comment by soaresden** [comment]
How did you do ? I just tried and always fastboot screen.. can't even boot on miui

**Comment by KaizerHanz** [comment]
I was give instruction on xda, but here tutorial what I'm doing to do :

after install riru-edxposed (YAHYA or Sandhok), reboot, then if you got "fastboot" mode, reboot to recovery and then go to file manager, go to data/adb/modules/riru-edxposed then search "post-fs-data.sh" (you can delete it or rename it). Then Reboot.

if you use stock kernel then you must have SELinux Permissive (you can google it app to make SELinux Enforced to Permissive).

**Comment by soaresden** [comment]
I just renamed via twrp explorer the file you said and all good now.
Many thanks !

**Comment by parambika** [comment]
> I was give instruction on xda, but here tutorial what I'm doing to do :
> 
> after install riru-edxposed (YAHYA or Sandhok), reboot, then if you got "fastboot" mode, reboot to recovery and then go to file manager, go to data/adb/modules/riru-edxposed then search "post-fs-data.sh" (you can delete it or rename it). Then Reboot.
> 
> if you use stock kernel then you must have SELinux Permissive (you can google it app to make SELinux Enforced to Permissive).

Thank you, this solves the problem of phone getting stuck on boot logo (splash screen), works on Redmi Note 5 Pro (whyred) Android 10 on Aosp based rom

**Comment by Mikanoshi** [comment]
Why 0.4.6.0 is spamming the log with
`E/EdXposed-Bridge: android.content.pm.PackageManager$NameNotFoundException:`
and also
`D/SandXposed: method <...> hook in`?

**Comment by ecompton59** [comment]
OnePlus 7pro oos 10.01 runs both good sandhook is faster i believe

**Comment by Udzi142** [comment]
Sadly not working on OnePlus 7T 10.0.4 (YAFHA or Sandhook)

**Comment by lllinusss** [comment]
It's sad that this simple fix works flawlessly while the official 4.6.0 beta release causes bootloops.

**Comment by remewer** [comment]
Thanks a lot for this. The official 0.4.6.0 doesn't work on my OnePlus 6 on Android 10 beta.

**Comment by iamMG** [comment]
Really lots of thanks! This version works woonders on my OnePlus 7 Pro OOS 10.0.1. Official version won't work.

**Comment by solohsu** [comment]
@kotori2 Sorry for late reply. What is the difference between this and #355 ?
@ganyao114

**Comment by kotori2** [comment]
@solohsu 
第一条commit是一样的，我从whale里修的权限，@ganyao114 在调whale之前修的权限，另外我写得比较丑
第二条是把sandhook的代码直接复制过来，然后照葫芦画瓢改了下XposedCompat.java
~~我也不知道我的fix那么长为什么反正it works~~

**Comment by solohsu** [comment]
@kotori2 嗯，按道理讲对whale的修改应该去whale那边提交PR。
现在我看很多人说你这个修改编译出来的没问题，#355 有问题。不清楚到底是哪里的差异造成的问题。

**Comment by kotori2** [comment]
> @kotori2 嗯，按道理讲对whale的修改应该去whale那边提交PR。
> 现在我看很多人说你这个修改编译出来的没问题，#355 有问题。不清楚到底是哪里的差异造成的问题。

idk
not tested
works on my device

**Comment by KenMizz** [comment]
虽然说是支持了Android 10但是最新commit的edxposed还是会在我的Oneplus 7 Pro上导致bootloop，只有这个才能用，为啥啊

**Comment by Howard20181** [comment]
> 虽然说是支持了Android 10但是最新commit的edxposed还是会在我的Oneplus 7 Pro上导致bootloop，只有这个才能用，为啥啊

试试这个呢？https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/27518070/artifacts

**Comment by KenMizz** [comment]
@Howard20181 谢谢

**Comment by p1r473** [comment]
Hi, I got myself in a pickle
Im on a Pixel 4 XL. I accidently installed EdXposed 0.4.5.1_beta instead of 0.4.6 and it caused a bootloop
I was able to get back into the OS by reflashing the latest OTA update, but I am left with a problem:
Any time I reflash Magisk, it recreates /data/adb/modules/riru-core and riru_edxposed_sandhook , the old versions that cause bootloop
No matter how many times I go in and delete these folders with ADB, they get recreated any time I reflash Magisk

How can I prevent Magisk from reinstalling these modules every boot? Please help!

**Comment by kotori2** [comment]
@p1r473 Create an empty file named "disable" in /data/adb/modules/blabla/

**Comment by kattza** [comment]
still get bootloops on miui 11.1 xiaomi.eu on both versions....
the only way I can get away with it is renaming the posts-fs-data.sh file but then EdXposed doens't work anyways on the modules, can anyone help? :/

**Comment by Noctfield** [comment]
[@Udzi142's reply](#issuecomment-544198847) still happens on OnePlus 7T, stock 10.0.7.HD65, with no other modules than `Riru core` and `EdXposed` installed. Since *TWRP* can't decrypt `/data`, the Magisk Manager for Recovery Mode aka `mm` is useless, and I had to flash a full system image to recover from the broken Magisk installation.

Note that only installing `EdXposed` will bootloop it - `Riru core` alone is fine.

**Comment by MlgmXyysd** [comment]
@Noctfield u can use Magisk rescue shell: "magisk --remove-modules" in bootloop-adb

**Comment by Noctfield** [comment]
@MlgmXyysd Thanks for the advice, will try next time when booting into recovery. The problem now is that I'm not quite confident about trying the SandHook variant 😐

**Comment by MlgmXyysd** [comment]
@Noctfield Note u must open adb and auth ur computer after bootloop

**Pull request closed without merging**
