### PR TITLE
Better Hidden & Module Scope

### PR DESCRIPTION
**Pull request by yujincheng08**
### Motivation
Many apps now detect Xposed's classes for security issues. EdXposed now provides an app list function to prevent hooking undesired apps. However, the classloader persists even if the app is blacklisted. The reason is that EdXposed load its java bridge and do some preliminary hooks in the zygote process and all subprocesses inherit them! Since both YAHFA and SandHook do not support unhooking, all the java bridge will be preserved in the process memory even if we remove all global references (SandHook and YAHFA hold some handling global references). Apps, therefore, can detect Xposed by checking the classloaders and the Xposed Bridge. To prevent such detection, one way is to load the Java bridge in the target process instead of the zygote process if the app is whitelisted.

### Implementation
To finish this mission, we should do as least things as possible in the zygote process, and do most of the jobs after forking. In the zygote process, we should not load any Java codes and do things purely in c++. Things that must be done in the zygote process are those that require special permission: reading the java bridge from the filesystem and loading configs. I, therefore, initialize the config manager in the zygote function and load dex files into byte arrays (but not loading them in ART). 
After forking, if the target process is not blacklisted, load the dex files into ART by using `InMemoryDexClassloader` and load all the modules from the preloaded list by absolute Apk paths. Otherwise, release all the memories in the c++ part inherit from the zygote process.

### Side effect
- Hooks are loaded later, some modules that require zygote permission will no longer work.
- `InitZygote`'s are called on every process. This behavior exists in EdXposed but is not desired by the original Xposed.
- The one plus workaround hook is removed. One Plus devices might not work.
- Slower launch if the app is hooked.

### Testing
Tested YAHFA in Mi10 AndroidQ MIUI and in x86 AndoirdR emulator. Tested and passed [Xposed Detector](https://github.com/vvb2060/XposedDetector). Some apps detecting Xposed like Deemo, China Mobile, and BOCHK are working.
More tests are requried.

### CODE REVIEW

**Comment by yujincheng08** [comment]
CI is not compatible with my PR. So I uploaded the built version for testing. DO AT YOUR OWN RISK.
[[riru21] EdXposed-YAHFA-v0.5.0.7-release.zip](https://github.com/ElderDrivers/EdXposed/files/5551198/riru21.EdXposed-YAHFA-v0.5.0.7-release.zip)
[[riru21] EdXposed-SandHook-v0.5.0.7-release.zip](https://github.com/ElderDrivers/EdXposed/files/5551197/riru21.EdXposed-SandHook-v0.5.0.7-release.zip)

[[riru22] EdXposed-YAHFA-v0.5.0.7-release.zip](https://github.com/ElderDrivers/EdXposed/files/5551182/riru22.EdXposed-YAHFA-v0.5.0.7-release.zip)
[[riru22] EdXposed-SandHook-v0.5.0.7-release.zip](https://github.com/ElderDrivers/EdXposed/files/5551183/riru22.EdXposed-SandHook-v0.5.0.7-release.zip)

**Comment by loveedxposed** [comment]
Since version 0.5, cannot hook isolated processes at initZygote's.Pls help me

**Comment by kotori2** [comment]
> cannot hook isolated processes at initZygote

Intended behavior.

**Comment by loveedxposed** [comment]
> > cannot hook isolated processes at initZygote
> 
> Intended behavior.

Yes, intended behavior. But some app can detect edxposed install.
https://darvincitech.wordpress.com/2019/11/04/detecting-magisk-hide/
i tried this project and detect path EdXposed in isolated processes, version 0.4 if "App List Mode" not enable, initZygote can hook isolated processes, but version 0.5 , cannot hook isolated processes ? Can you help me ?

**Comment by yujincheng08** [comment]
@loveedxposed never ever hook isolated process. it will lead to crashing (like chromium)

**Comment by loveedxposed** [comment]
> @loveedxposed never ever hook isolated process. it will lead to crashing (like chromium)

Yes, i'm know, but version edxposed 0.4 can hook function in isolated process and bypass it.
If app detect edxposed in isolated process, how to bypass in version 0.5 ?
"Xposed Hide" above cannot bypass. Would you like me to send source code detect edxposed in isolated processes ?

**Comment by yujincheng08** [comment]
I think that's because Magisk hide doesn't work on isolated processes and is none of EdXposed's business.

**Comment by loveedxposed** [comment]
> I think that's because Magisk hide doesn't work on isolated processes and is none of EdXposed's business.

Magisk Hide doesn't work, but i'm try edxposed 0.4 and riru 21.3 working fine. Hope this information will be of help to you. Have a nice day

**Pull request merged**
