### PR TITLE
YAHFA: Support for android 10

### PR DESCRIPTION
**Pull request by aviraxp**
Change-Id: I8d31014abff1ed15919ab10604a90be52d96c3a6

### CODE REVIEW

**Comment by MlgmXyysd** [comment]
What problem is fixed?

**Comment by aviraxp** [comment]
https://github.com/Project-OneOS/art/commit/9581e6176c78f3f2a8f40ff9d5a6c4d4029253fb#diff-4da92dc1ed9aa56d315ead7121282fe0R73

We should clear this flag if target method is native.
Not sure if I port it correctly. cc @paulo-raca  can you take a look?

**Comment by aviraxp** [comment]
Seems work fine here.

**Comment by paulo-raca** [comment]
I'm not the author of these changes, I just ported them to YAHFA, but as far as I understand it  must disable the fast path -- and sets the `native` flag to ensure it stays disabled

**Comment by paulo-raca** [comment]
AFAICT, your port seems equivalent to my code :+1:

**Comment by MlgmXyysd** [comment]
Thanks for contributing

**Pull request merged**
