### PR TITLE
Fix Snapchat Detection

### PR DESCRIPTION
**Pull request by Juxstin**
Fix Snapchat Detection the last users who committed accidentally commited my work so heres mine.

### CODE REVIEW

**Comment by AeonLucid** [comment]
Where did you find that this was causing bans? [I couldn't find that anywhere or anything else related to EdXposed.](https://aeonlucid.com/Snapchat-detection-on-Android/)

**Comment by Juxstin** [comment]
@AeonLucid It just does. Kinda hard to explain. Test it yourself

**Comment by AeonLucid** [comment]
@solohsu I don't believe this should be merged. It does fix Snapchat detection for P because they are checking the method modifiers of `void handleBindApplication(AppBindData)`. Using this PR, said method does not get hooked by EdXposed thus the method modifiers appear normal to Snapchat.

**Comment by Juxstin** [comment]
@solohsu add a option to disable them? is that possible?

**Comment by immiteshk** [comment]
So, is there any way to use snapchat with edxposed? I have been locked out.

**Comment by Juxstin** [comment]
@immiteshk https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases 

Use this till they fork / apply a fix :)

**Comment by davex2012** [comment]
> @immiteshk https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases
> 
> Use this till they fork / apply a fix :)

Tried to flash magisk-EdXposed-SandHook-v0.4.5.5_beta-release.zip and YAHA but both it said installed, but not activated what should i do?

**Comment by csin86** [comment]
> > @immiteshk https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases
> > Use this till they fork / apply a fix :)
> 
> Tried to flash magisk-EdXposed-SandHook-v0.4.5.5_beta-release.zip and YAHA but both it said installed, but not activated what should i do?

I had this issue too. I installed riru core then rebooted and then installed YAHFA then rebooted. I assumed that it would work after rebooting the second time but in EdXposed installer it said the framework was "not activated". So, I rebooted one more time (third time now), which did the trick, and now it says activated.

**Comment by MlgmXyysd** [comment]
Since all checks have failed, so this pr will be closed, you can reopen if you fix these checks.

**Pull request closed without merging**
