### PR TITLE
Opt-in automatic preferences file migration

### LINKED ISSUE #751: [PROPOSAL] Automatic handling of old preferences files
The new preferences location redirection hook works great, but there is no easy way of migrating preferences from old location to the new one.
The built-in hook should try to move the preferences files to the new location.

Things to consider:
- Whether to move all files preemptively or check each file when it's requested from app or module side
- Old files might be stored in either `/data/data/` or `/data/user_de/0/` (should those be redirected as well?)
- The files may have dirty other tricks applied on them, chmod/chown/selinux reset might be necessary

### PR DESCRIPTION
**Pull request by XspeedPL**
Resolves #751.
Migration is opt-in.
All files are migrated automatically, from the directory they are requested by the app (either `data` or `user_de`).
File attributes are preserved by the NIO api.
Symlinks are put in place of old files for compatibility with other (root) applications trying to read preferences.

Module developers need a mechanism to detect file changes made by the migration.

### CODE REVIEW

**Comment by kotori2** [comment]
@yujincheng08

**Comment by yujincheng08** [comment]
> @yujincheng08 

？

**Comment by XspeedPL** [comment]
This second commit was not supposed to be a part of this pull request.

Since it is now, let me explain a bit:
The changes to XSharedPreferences provide module developers with a mechanism to easily detect preference file changes via the unused OnSharedPreferenceChangeListener interface, so no API is actually changed.
The mechanism is implemented using a global WatchService with indivitual XSP instances registering their own file in the watchlist.
Changes are monitored by a per-process daemon thread, and report to the modules when either file size or hash change is detected.
Small bits of trickery are applied inside the thread to ignore SharedPreferences backup writing behavior.

**Comment by kotori2** [comment]
I'm not familiar with Java tricks so someone review this pls.
The concept lgtm anyway.

**Pull request merged**
